"""training/calibrate.py

Measures the rejection thresholds instead of guessing them, and writes both
shared/wand_thresholds.h and the mirrored block in wand_config.py.

    python calibrate.py --data data/raw --misfire-budget 0.0

METHOD
    1.  Run the full leave-one-caster-out loop and pool every held-out softmax
        vector.  These are out-of-sample probabilities from casters the model has
        never seen -- the closest thing available to a judge's hand.
    2.  Sweep (tau, margin) on a fine grid and, for each point, measure:
            recall   -- spells correctly fired, over all spells presented
            misfire  -- windows that fired the WRONG spell, or fired at all on a
                        NOISE window.  This is the quantity the PS penalises.
            silent   -- spells that were presented and produced nothing
    3.  Choose the point with the highest recall whose misfire rate is inside the
        budget.  Ties break toward the LARGER margin, because margin failures are
        the Lumos/Alohomora confusions and those are the ones a judge will
        reproduce deliberately.

WHY A BUDGET OF ZERO IS THE DEFAULT
    Under this PS a misfire is penalised and a silent wand merely scores nothing.
    The asymmetry is not subtle, so the default operating point is the most
    permissive setting that still misfires zero times out of sample.  Raise the
    budget only if recall is so low the wand feels broken to a caster -- and if
    you do, say so in the report and quote both numbers.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np
from tensorflow import keras

import wand_config as C
from dataset import load_dataset, loco_folds, to_arrays
from train_cnn import train_fold

NOISE = int(C.WandGestureClass.NOISE)


def operating_point(probs: np.ndarray, y: np.ndarray, budget: float):
    order = np.argsort(probs, axis=1)
    top1 = order[:, -1]
    p1 = probs[np.arange(len(probs)), order[:, -1]]
    p2 = probs[np.arange(len(probs)), order[:, -2]]
    pn = probs[:, NOISE]
    is_spell = y != NOISE

    best = None
    rows = []
    for tau in np.arange(0.30, 0.96, 0.025):
        for margin in np.arange(0.00, 0.61, 0.025):
            for tn in (0.35, 0.50):
                fire = (top1 != NOISE) & (p1 >= tau) & ((p1 - p2) >= margin) & (pn < tn)
                hit = fire & is_spell & (top1 == y)
                mis = fire & (~is_spell | (top1 != y))
                recall = hit.sum() / max(is_spell.sum(), 1)
                misfire = mis.sum() / max(len(y), 1)
                rows.append((tau, margin, tn, recall, misfire))
                if misfire <= budget:
                    key = (recall, margin)
                    if best is None or key > (best[3], best[1]):
                        best = (tau, margin, tn, recall, misfire)
    return best, rows


def write_header(path: Path, tau: float, margin: float, tn: float,
                 recall: float, misfire: float, synthetic: bool) -> None:
    status = 0 if synthetic else 1
    note = ("// STATUS: SYNTHETIC CALIBRATION -- rerun on real captures before the demo"
            if synthetic else "// STATUS: calibrated on real leave-one-caster-out probabilities")
    path.write_text(f"""// shared/wand_thresholds.h
// AUTO-GENERATED by training/calibrate.py.  Do not hand-edit.
//
// These three constants are measurements taken from the pooled leave-one-caster-out
// softmax distribution, not design choices.  A threshold picked by intuition is
// incompatible with label smoothing: a model that is 100% correct by argmax can
// still fail an arbitrary 0.80 confidence gate on more than half its predictions.
//
// Regenerate with:  python training/calibrate.py --data data/raw
#ifndef WAND_THRESHOLDS_H
#define WAND_THRESHOLDS_H

{note}
#define WAND_THRESHOLDS_CALIBRATED {status}

constexpr float REJ_TAU_CONF   = {tau:.3f}f;   // top-1 probability floor
constexpr float REJ_TAU_MARGIN = {margin:.3f}f;   // top1 - top2
constexpr float REJ_TAU_NOISE  = {tn:.3f}f;   // hard veto on P(NOISE)

// Operating point achieved at these thresholds, out of sample:
constexpr float CAL_RECALL_AT_OP  = {recall:.4f}f;
constexpr float CAL_MISFIRE_AT_OP = {misfire:.4f}f;

#endif  // WAND_THRESHOLDS_H
""")


def patch_python(path: Path, tau: float, margin: float, tn: float, synthetic: bool) -> None:
    src = path.read_text()
    src = re.sub(r"THRESHOLDS_CALIBRATED = \w+", f"THRESHOLDS_CALIBRATED = {not synthetic}", src)
    src = re.sub(r"REJ_TAU_CONF = [\d.]+", f"REJ_TAU_CONF = {tau:.3f}", src)
    src = re.sub(r"REJ_TAU_MARGIN = [\d.]+", f"REJ_TAU_MARGIN = {margin:.3f}", src)
    src = re.sub(r"REJ_TAU_NOISE = [\d.]+", f"REJ_TAU_NOISE = {tn:.3f}", src)
    path.write_text(src)


def report_gate_percentiles(caps) -> None:
    """The recalibration rule for the Stage 1 kinematic gate.

    Stage 1 is a cheap pre-filter, not a classifier, and its job description is
    asymmetric: it must almost never reject a real spell (a rejected spell is a
    lost point and the network never gets a say), while any noise it happens to
    stop is a bonus that saves 5 ms of inference. So the floors are set from the
    REAL spell distribution -- at roughly its 1st percentile -- and never from
    intuition about what noise looks like. Discriminating noise is Stage 2's job,
    and Stage 2 is a trained network with an actual NOISE class.

    Print this after collection. The marginal distributions below are diagnostic
    only -- the floors themselves come from the joint sweep underneath, because
    the gate is a DISJUNCTION and a per-feature percentile cannot see that.
    """
    import wand_config as _C
    spells = [c.kin for c in caps if c.label != NOISE]
    if not spells:
        return
    print("\nStage 1 gate -- spell distribution (diagnostic; floors come from the sweep):")
    print(f"{'feature':<14}{'p1':>8}{'p50':>8}{'p99':>8}   current")
    for name, vals, cur in [
        ("peak_w", [k.peak_w for k in spells], _C.REJ_MIN_PEAK_W),
        ("path_rad", [k.path_rad for k in spells], _C.REJ_MIN_PATH_RAD),
        ("peak_a", [k.peak_a for k in spells], _C.REJ_MIN_PEAK_A),
        ("duration_s", [k.duration_s for k in spells], _C.REJ_MIN_DURATION_S),
    ]:
        p1, p50, p99 = np.percentile(vals, [1, 50, 99])
        print(f"{name:<14}{p1:>8.2f}{p50:>8.2f}{p99:>8.2f}   {cur:.2f}")

    sweep_energy_gate(caps)
    sweep_spike_test(caps)
    sweep_duration_gate(caps)


def sweep_duration_gate(caps, budget: float = 0.01) -> None:
    """Choose REJ_MIN_DURATION_S from the real spell-duration distribution.

    This floor was previously a fixed design constant (0.60s, chosen to leave
    "0.30s of actual gesture" after the 0.2s pre-roll + 0.1s post-roll), never
    swept the way the energy gate and impact test are -- because until real
    casters existed there was no duration distribution to sweep against. The
    first real corpus showed it mattered: several spells (Wingardium Leviosa,
    Alohomora) are performed by real casters noticeably faster than a 0.60s
    floor allows, and a gate that eats a third to three-quarters of real casts
    is not doing its job of "did anything happen at all" -- it is functioning
    as a second, uncalibrated classifier.

    Same rule as the other two sweeps: take the LARGEST floor (best at
    rejecting genuinely-too-brief noise blips) whose real spell loss stays
    inside the budget, never the floor that looks best in isolation.
    """
    import wand_config as _C
    S = [c.kin for c in caps if c.label != NOISE]
    N = [c.kin for c in caps if c.label == NOISE]
    if not S:
        return

    print(f"\nStage 1 duration floor -- sweep (largest floor, spell loss <= "
          f"{budget*100:.0f}%):")
    print(f"{'floor_s':>9}{'spell loss':>13}{'noise stopped':>15}")
    best = None
    for lo in (0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60):
        loss = sum(1 for k in S if k.duration_s < lo) / len(S)
        stop = (sum(1 for k in N if k.duration_s < lo) / len(N)) if N else 0.0
        mark = ""
        if loss <= budget and (best is None or lo > best[0]):
            best = (lo, loss, stop)
            mark = "  <-- best so far"
        print(f"{lo:9.2f}{loss*100:12.1f}%{stop*100:14.1f}%{mark}")
    if best:
        lo, loss, stop = best
        print(f"\n  choose REJ_MIN_DURATION_S = {lo:.2f}  (spell loss {loss*100:.1f}%, "
              f"noise-too-brief caught {stop*100:.1f}%)")
        print(f"  currently {_C.REJ_MIN_DURATION_S:.2f}")
    else:
        print(f"  no floor in this grid keeps spell loss <= {budget*100:.0f}% -- "
              f"real casts are shorter than even the lowest candidate; this is a\n"
              f"  coaching problem (casters performing too fast), not one this gate "
              f"can be tuned around")


def sweep_energy_gate(caps, budget: float = 0.01) -> None:
    """Choose REJ_MIN_PEAK_W, REJ_MIN_PATH_RAD and REJ_MIN_PEAK_A jointly.

    These three do not act independently -- the gate fires if a window is
    rotationally energetic (peak_w AND path_rad) OR ballistically energetic
    (peak_a) -- so setting each one from its own marginal percentile is the wrong
    operation. A Stupefy has almost no path_rad and does not need any; reading
    the p1 of path_rad over ALL spells therefore drags the rotational floor down
    to a value chosen by a class that never uses that arm.

    So sweep the triple, evaluate the disjunction exactly as reject.cpp does, and
    take the point that stops the most noise subject to a small budget of spell
    loss. The budget is not zero, deliberately: with the lever-arm physics
    modelled, a gentle cast from a light-handed caster genuinely does land near
    the floor, and a hard zero-loss constraint just picks whichever corner of the
    grid happens to be degenerate.
    """
    import wand_config as _C
    S = [c.kin for c in caps if c.label != NOISE]
    N = [c.kin for c in caps if c.label == NOISE]
    if not S or not N:
        return

    def passes(k, W, P, A):
        return (k.peak_w >= W and k.path_rad >= P) or (k.peak_a >= A)

    print(f"\nStage 1 energy gate -- joint sweep (max noise stopped, "
          f"spell loss <= {budget*100:.0f}%):")
    best = None
    for W in (1.2, 1.6, 2.0, 2.4, 2.8, 3.2):
        for P in (0.4, 0.7, 1.0, 1.4, 1.8):
            for A in (1.2, 1.5, 1.8, 2.1, 2.5):
                loss = sum(1 for k in S if not passes(k, W, P, A)) / len(S)
                stop = sum(1 for k in N if not passes(k, W, P, A)) / len(N)
                if loss <= budget and (best is None or stop > best[4]):
                    best = (W, P, A, loss, stop)
    if best:
        W, P, A, loss, stop = best
        print(f"  choose REJ_MIN_PEAK_W = {W:.2f}, REJ_MIN_PATH_RAD = {P:.2f}, "
              f"REJ_MIN_PEAK_A = {A:.2f}")
        print(f"    spell loss {loss*100:.1f}%, noise stopped {stop*100:.1f}%")
        print(f"  currently {_C.REJ_MIN_PEAK_W:.2f} / {_C.REJ_MIN_PATH_RAD:.2f} "
              f"/ {_C.REJ_MIN_PEAK_A:.2f}")
    else:
        print(f"  no point meets a {budget*100:.0f}% loss budget -- widen the grid")


def sweep_spike_test(caps, budget: float = 0.01) -> None:
    """Choose REJ_SPIKE_G and REJ_SPIKE_MIN_RUN from data, on the same rule.

    The impact test is two-dimensional -- a level and a width -- so it cannot be
    read off a percentile at all. Sweep the pair and take the point that catches
    the most noise subject to the same small budget of spell false-rejection.

    Getting this wrong is not hypothetical, twice over. At the level and width
    first chosen by intuition (2.40 g, 4 samples) the test rejected 9% of Stupefy
    -- the bonus spell, whose whole signature is a large acceleration -- while
    catching only 4% of noise. And the sweep that replaced it originally stopped
    at 2.4 g, because R3 believed 3 g was the ceiling; once the lever-arm physics
    put real casts up at 5 g, that ceiling was inside the search space rather
    than outside it, and a sweep whose grid stops short does not report that it
    stopped short -- it reports a winner.
    """
    import wand_config as _C
    from preprocess import to_physical
    from dataset import _read_csv

    def peak_and_run(cap, level):
        raw, _, _, _ = _read_csv(cap.path)
        _, acc, _ = to_physical(raw)
        am = np.linalg.norm(acc, axis=1)
        run = best = 0
        for v in am:
            run = run + 1 if v >= level else 0
            best = max(best, run)
        return float(am.max()), best

    spells = [c for c in caps if c.label != NOISE]
    noise = [c for c in caps if c.label == NOISE]
    if not spells or not noise:
        return

    print(f"\nStage 1 impact test -- sweep (max noise caught, spell loss <= "
          f"{budget*100:.0f}%):")
    print(f"{'spike_g':>9}{'min_run':>9}{'spell FALSE-REJ':>17}{'noise caught':>14}")
    best = None
    # The level range runs to 4.4 g because the reportable range is +/-5 g per
    # axis, not the 3 g R3 assumed.  A sweep that stops at 2.4 -- as this one did
    # before the geometry was modelled -- cannot see that the best operating
    # point is above its own ceiling, and reports a "best" that is merely the
    # least bad of the points it looked at.
    for level in (1.8, 2.0, 2.4, 2.8, 3.2, 3.6, 4.0, 4.4):
        S = [peak_and_run(c, level) for c in spells]
        N = [peak_and_run(c, level) for c in noise]
        for width in (2, 3, 4, 6, 8):
            fr = sum(1 for p, b in S if p >= level and b < width) / len(S)
            ct = sum(1 for p, b in N if p >= level and b < width) / len(N)
            mark = ""
            if fr <= budget and (best is None or ct > best[3]):
                best = (level, width, fr, ct)
                mark = "  <-- best so far"
            print(f"{level:9.1f}{width:9d}{fr*100:>16.1f}%{ct*100:>13.1f}%{mark}")
    if best:
        print(f"\n  choose REJ_SPIKE_G = {best[0]:.2f}, REJ_SPIKE_MIN_RUN = {best[1]}"
              f"  (spell loss {best[2]*100:.1f}%, noise caught {best[3]*100:.1f}%)")
        print(f"  currently {_C.REJ_SPIKE_G:.2f} / {_C.REJ_SPIKE_MIN_RUN}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default=C.REAL_DATA_DIR)
    ap.add_argument("--allow-synthetic", action="store_true")
    ap.add_argument("--misfire-budget", type=float, default=0.0)
    ap.add_argument("--epochs", type=int, default=80)
    ap.add_argument("--aug", type=int, default=8)
    # Anchored to the repo root rather than bare relative strings -- see the
    # matching fix and comment in wand_config._REPO_ROOT / train_cnn.py's --out.
    ap.add_argument("--header", default=str(C._REPO_ROOT / "shared" / "wand_thresholds.h"))
    ap.add_argument("--pyconfig", default=str(C._REPO_ROOT / "training" / "wand_config.py"))
    args = ap.parse_args()

    caps = load_dataset(args.data, allow_synthetic=args.allow_synthetic)
    synthetic = any(c.synthetic for c in caps)
    stamp = "SYNTHETIC -- NOT A RESULT | " if synthetic else ""
    X, y, g = to_arrays(caps)
    report_gate_percentiles(caps)

    # The softmax thresholds below need POOLED, OUT-OF-SAMPLE probabilities --
    # held-out casters the model never trained on -- which is structurally
    # impossible with one caster (loco_folds would yield an empty train split
    # and crash deep inside augment_dataset()'s stack(), the same failure
    # train_cnn.py hit). Stop here, loudly, rather than either crash on a
    # numpy internals traceback or silently write a same-caster-split number
    # that LOOKS calibrated but is not: a threshold fit on one person's own
    # held-back reps is still fit to that person's hand.
    n_casters = len(set(g))
    if n_casters < 2:
        print(f"\n{stamp}STOPPING before threshold calibration: only {n_casters} "
              f"caster(s) present, need >= 2 for an out-of-sample operating point.")
        print(f"{stamp}The duration/energy/impact sweeps above already ran on this "
              f"caster's real kinematics and are worth applying now. The three "
              f"softmax thresholds in {args.header.split('/')[-1]} are left as "
              f"whatever they currently are (WAND_THRESHOLDS_CALIBRATED unchanged) "
              f"-- do not hand-edit them to something that looks plausible; rerun "
              f"this script once a second caster's data exists.")
        return

    P, Y = [], []
    for caster, tr, te in loco_folds(g):
        m = train_fold(X[tr], y[tr], X[te], y[te], epochs=args.epochs, aug_factor=args.aug)
        P.append(m.predict(X[te], verbose=0))
        Y.append(y[te])
        print(f"{stamp}fold {caster} done ({te.sum()} held out)")
        keras.backend.clear_session()
    P, Y = np.concatenate(P), np.concatenate(Y)

    best, rows = operating_point(P, Y, args.misfire_budget)
    if best is None:
        raise SystemExit(f"no operating point meets a misfire budget of "
                         f"{args.misfire_budget}; the model is not good enough yet")
    tau, margin, tn, recall, misfire = best
    print(f"\n{stamp}chosen operating point: tau={tau:.3f} margin={margin:.3f} "
          f"tau_noise={tn:.2f}  ->  recall={recall:.3f} misfire={misfire:.4f}")

    write_header(Path(args.header), tau, margin, tn, recall, misfire, synthetic)
    patch_python(Path(args.pyconfig), tau, margin, tn, synthetic)
    print(f"wrote {args.header} and patched {args.pyconfig}")
    if synthetic:
        print("!! calibrated on synthetic data -- these thresholds are NOT valid; "
              "rerun on data/raw before the demo build")


if __name__ == "__main__":
    main()
