// shared/wand_thresholds.h
// AUTO-GENERATED by training/calibrate.py.  Do not hand-edit.
//
// These three constants are measurements taken from the pooled leave-one-caster-out
// softmax distribution, not design choices.  A threshold picked by intuition is
// incompatible with label smoothing: a model that is 100% correct by argmax can
// still fail an arbitrary 0.80 confidence gate on more than half its predictions.
//
// Regenerate with:  python training/calibrate.py --data data/raw
#ifndef WAND_THRESHOLDS_H
#define WAND_THRESHOLDS_H

// STATUS: SYNTHETIC CALIBRATION -- rerun on real captures before the demo
#define WAND_THRESHOLDS_CALIBRATED 0

constexpr float REJ_TAU_CONF   = 0.300f;   // top-1 probability floor
constexpr float REJ_TAU_MARGIN = 0.100f;   // top1 - top2
constexpr float REJ_TAU_NOISE  = 0.350f;   // hard veto on P(NOISE)

// Operating point achieved at these thresholds, out of sample:
constexpr float CAL_RECALL_AT_OP  = 0.9648f;
constexpr float CAL_MISFIRE_AT_OP = 0.0000f;

#endif  // WAND_THRESHOLDS_H
